_wandb:
    value:
        cli_version: 0.22.1
        e:
            k6tdqlsdjxaygqhqxv7fp34mofkk9iaz:
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1006450962432"
                        used: "147542974464"
                email: Desa2thomas@gmail.com
                executable: /home/tom/.virtualenvs/ml-research/bin/python
                git:
                    commit: 5990cd6b054906a93afd4fd01d4ab65d6a974d94
                    remote: https://github.com/wlu-labs/research-students-fall-2025-desa-thomas.git
                host: groundControl
                memory:
                    total: "16048361472"
                os: Linux-6.17.7-arch1-1-x86_64-with-glibc2.42
                program: <python with no main file>
                python: CPython 3.11.13
                root: /home/tom/projects/FL-research-25
                startedAt: "2025-11-21T20:31:43.089946Z"
                writerId: k6tdqlsdjxaygqhqxv7fp34mofkk9iaz
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 13
                - 61
            "4": 3.11.13
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
